### ISSUE TITLE
Site Blueprint

### ISSUE THREAD

**Issue by AugustMiller** [PSUGraphicDesign/be-honest#5]
Top-level site data will include:

- [ ] Social Media Links
- [ ] Contact Information
- [ ] Credits for Design & Development
- [ ] Department Information (PSU, School of Art + Design)
- [ ] Meta Tags
- [ ] Meta Description
- [ ] Analytics Data

I don't anticipate this content changing much event-to-event, so we'll pull it up out of the _Event_ Blueprint and make it global.

**Comment by donnatruong** [comment]
There's also a section that lists and stacks all the names of the past speakers. Wondering if it would go here as well?

**Comment by AugustMiller** [comment]
Interesting— a _full_ list could get really long after this year (the number of speaker "alumni" will have doubled after this event), so doing it automatically might be troublesome, not to mention the fact that we just don't have a spot to enter past speakers.

I'd propose a `structure` field, like this:

```yaml
past_speakers:
  label: Past Speakers
  type: structure
  entry: >
    <strong>{{name}}</strong> ({{year}})
  fields:
    name:
      label: Name
      type: text
    year:
      label: Year
      type: number
      icon: calendar-o
    website:
      label: Website
      type: url
  help: >
    Enter any speakers you'd like to feature in the footer of the site. They'll display in the order above.
```
